swagger: '2.0'
info:
  title: Cloud Endpoints
  description: Public API for mihirlad.com
  version: 1.0.0
host: esp-4sqqeyzcba-uc.a.run.app
schemes:
  - https
produces:
  - application/json
definitions:
  Stat:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      value:
        type: string
paths:
  /get-stats:
    get:
      summary: Get latest stats
      operationId: get-stats
      x-google-backend:
        address: https://us-central1-mihirlad-website.cloudfunctions.net/get-stats
        protocol: h2
      produces:
        - application/json
      responses:
        '200':
          description: A successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Stat'

