runtime: nodejs12
service: default
instance_class: F1

default_expiration: "180d"

handlers:
- url: /
  static_files: dist/mihirlad/index.html
  upload: dist/mihirlad/index.html
  secure: always
  expiration: "1h"

- url: /(github|gitlab|linkedin|meet)$
  static_files: dist/mihirlad/index.html
  upload: dist/mihirlad/index.html
  secure: always
  expiration: "1m"

- url: /assets/json/(.*)
  static_files: dist/mihirlad/assets/json/\1
  upload: dist/mihirlad/assets/json/(.*)
  secure: always
  expiration: "1d"

- url: /(.*)
  static_files: dist/mihirlad/\1
  upload: dist/mihirlad/(.*)
  secure: always
