name: Production CI/CD

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  GITHUB_AUTH_TOKEN: ${{ secrets.GET_STATS_GITHUB_AUTH_TOKEN }}

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: Build angular project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup npm
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install node dependencies
        run: npm install
      - name: Build
        run: npm run ng build -- --prod --optimization=true
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist/mihirlad

  deploy_production:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Download dist artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/mihirlad
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy app.yaml
        run: gcloud app deploy app.yaml
      - name: Deploy dispatch.yaml
        run: gcloud app deploy dispatch.yaml
      - name: Deploy update-stats cloud function
        run: gcloud functions deploy update-stats --entry-point updateStats --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-topic='update-stats' --service-account='update-stats-function@mihirlad-website.iam.gserviceaccount.com' --set-env-vars="GITHUB_AUTH_TOKEN=${GET_STATS_GITHUB_AUTH_TOKEN}"
      - name: Deploy get-stats cloud function
        run: gcloud functions deploy get-stats --entry-point getStats --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-http --service-account='get-stats-function@mihirlad-website.iam.gserviceaccount.com' --allow-unauthenticated
      - name: Deploy endpoints services proxy
        run: gcloud run deploy esp --image='gcr.io/endpoints-release/endpoints-runtime-serverless:2' --allow-unauthenticated --platform managed --region us-central1 --service-account='esp-run@mihirlad-website.iam.gserviceaccount.com'
      - name: Deploy endpoints api
        run: gcloud endpoints services deploy src/endpoints/openapi-functions.yaml
