name: Production CI/CD

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  GITHUB_AUTH_TOKEN_SECRET_NAME: ${{ secrets.AUTH_TOKEN_SECRET_NAME }}

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    name: Build angular project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: sudo apt-get install webp
      - name: Generate webp and jpg images
        run: ./scripts/convert-images.sh
      - name: Setup npm
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install node dependencies
        run: npm install
      - name: Build
        run: npm run ng build -c prod --optimization=true
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist/mihirlad

  deploy_update_stats_function:
    name: Deploy update_stats cloud function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy update-stats cloud function
        run: gcloud functions deploy update-stats --entry-point updateStats --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-topic='update-stats' --service-account='update-stats-function@mihirlad-website.iam.gserviceaccount.com' --set-env-vars="GITHUB_AUTH_TOKEN_SECRET_NAME=${GITHUB_AUTH_TOKEN_SECRET_NAME}"

  deploy_get_stats_function:
    name: Deploy get_stats cloud function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy get-stats cloud function
        run: gcloud functions deploy get-stats --entry-point getStats --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-http --service-account='get-stats-function@mihirlad-website.iam.gserviceaccount.com' --allow-unauthenticated

  deploy_update_projects_function:
    name: Deploy update_stats cloud function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy update-projects cloud function
        run: gcloud functions deploy update-projects --entry-point updateProjects --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-topic='update-projects' --service-account='update-projects-function@mihirlad-website.iam.gserviceaccount.com' --set-env-vars="GITHUB_AUTH_TOKEN_SECRET_NAME=${GITHUB_AUTH_TOKEN_SECRET_NAME},BASE_PROJECTS_URL=https://mihirlad.com/assets/json/projects.json"

  deploy_get_projects_function:
    name: Deploy get_projects cloud function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy get-projects cloud function
        run: gcloud functions deploy get-projects --entry-point getProjects --runtime=nodejs12 --source='src/functions' --timeout='60s' --trigger-http --service-account='get-projects-function@mihirlad-website.iam.gserviceaccount.com' --allow-unauthenticated

  deploy_app_production:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Download dist artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/mihirlad
      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
      - name: Deploy app.yaml
        run: gcloud app deploy app.yaml
      - name: Deploy dispatch.yaml
        run: gcloud app deploy dispatch.yaml
